global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "user-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["user-service:8080"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "user-service"

  - job_name: "trip-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["trip-service:8081"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "trip-service"

  - job_name: "driver-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["driver-service:3001"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "driver-service"
